# Generated by Django 5.2.5 on 2025-08-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='like',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='like',
            name='heroi',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
    ]
