# Generated by Django 5.2.5 on 2025-09-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_pow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pow',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post'),
        ),
    ]
