# Generated by Django 5.2.5 on 2025-08-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='codinome',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='poderes',
        ),
    ]
