# Generated by Django 5.2.5 on 2025-09-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_hero_codinome_remove_hero_criado_em_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
