# Generated by Django 5.2.5 on 2025-09-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_contato',
            field=models.TextField(blank='Nenhum'),
        ),
    ]
