"""
Django settings for superbook project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

from dotenv import load_dotenv  # Importa
import dj_database_url

# Carrega as variáveis do .env para o ambiente
load_dotenv()

SOCIALACCOUNT_LOGIN_ON_GET = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r0br$iv&n$_-6+a*h+_hl858vp_)!_cerc!0g7!d#67oif2*jw'

# Mude DEBUG para ler do .env. Em produção, será 'False'
# O 'False' como string é importante para o os.environ.get
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    '.onrender.com',
    '127.0.0.1',
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'feed',
    'perfil',
    'posts',
    'usuarios',
    'comentarios',
    'viloes',

    # ... apps do django
    'django.contrib.sites',  # <-- Necessário para o allauth

    # Apps do Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Provider específico (Google)
    'allauth.socialaccount.providers.google',
]

# settings.py

try:
    GOOGLE_CLIENT_ID = os.environ['GOOGLE_CLIENT_ID']
    GOOGLE_CLIENT_SECRET = os.environ['GOOGLE_CLIENT_SECRET']
    print("--- TESTE DE DEBUG DO .ENV ---")
    print(f"CLIENT ID LIDO: {GOOGLE_CLIENT_ID}")
    print(f"CLIENT SECRET LIDO: {GOOGLE_CLIENT_SECRET}")
    print("------------------------------")
except KeyError:
    raise Exception(
        "Erro: GOOGLE_CLIENT_ID ou GOOGLE_CLIENT_SECRET não foram encontrados no .env! "
        "Verifique se o .env existe e reinicie o servidor."
    )

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Adicione esta linha:
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'superbook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'superbook.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# Para onde o 'collectstatic' vai copiar os arquivos
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# Configuração do WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ARQUIVOS DE MÍDIA (Uploads de Foto)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py
SITE_ID = 1

# settings.py
AUTHENTICATION_BACKENDS = [
    # Necessário para logar no admin com usuário e senha
    'django.contrib.auth.backends.ModelBackend',

    # Backend de autenticação específico do allauth
    'allauth.account.auth_backends.AuthenticationBackend',
]

# settings.py
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # O que vamos pedir ao Google
        'SCOPE': [
            'profile',
            'email',
        ],
        # Como vamos pedir (login padrão)
        'AUTH_PARAMS': {
            'access_type': 'online',
        },

        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': ''  # Deixe vazio
        }
    }
}

# settings.py
LOGIN_REDIRECT_URL = '/plataforma'  # Vai para a página inicial
LOGOUT_REDIRECT_URL = '/auth/login/' # Vai para a página inicial